- name: linux packages
  block:
    - name: install epel repository
      package:
        name: epel-release
      when:
      - ansible_os_family == "RedHat"
      - dots_enable_epel_repo

    - name: install linux packages
      package:
        state: present
        name: "{{ dots_os_packages }}"
      when: ansible_system == "Linux"

- name: mac os packages
  block:
    - name: install homebrew packages
      homebrew:
        state: present
        name: "{{ dots_homebrew_packages }}"
        update_homebrew: true

    - name:
      homebrew_cask:
        name: "{{ dots_cask_packages }}"
        state: present
        update_homebrew: true
  when: ansible_system == "Darwin"
