---
dots_homebrew_packages:
  - git
  - zsh
  - htop
  - nmap
  - packer

dots_cask_packages:
  - docker
  - firefox
  - google-chrome
  - homebrew/cask-drivers/logitech-options
  - iterm2
  - macpass
  - rectangle
  - spotify
  - transmission
  - vagrant
  - virtualbox
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
  - google-drive-file-stream
  - open-in-code
