set list							" showing newline as $
set number						" show line numbers
syntax on							" set syntax highlighting on
set tabstop=2					" tabs in files are four spaces
set softtabstop=2			" same as tabstop but for my one <TAB>
set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<	" showing invisible chars
