# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/.local/bin:$HOME/bin:$PATH
ZSH_DISABLE_COMPFIX=true

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="myowntheme"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=${HOME}/.zshrc_custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git aws colored-man-pages)

source $ZSH/oh-my-zsh.sh

# User configuration

# Use vim as default editor
export EDITOR='vim'

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# Adds possibility to go back to the parent folder with cd ..<TAB>
zstyle ':completion:*' special-dirs true

# Disable Beep in terminal
setopt NO_BEEP

# User aliases
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias hgrep='history 0 |grep --color=auto '
alias fuck='sudo `fc -n -l -1 `'
alias please=fuck
alias ports='netstat -tlpen'
# git aliase
alias ggrep='git grep'
alias gst='git status'
alias gad='git add'
alias gadd=gad
alias gcom='git commit -v'
alias gom=gcom
alias giff='git diff'
# No glob aliases
alias find='noglob find'
alias systemctl='noglob systemctl'
# Alias for sourcing .zshrc
alias zre='source ~/.zshrc'

# System upgrade alias
if [[ -f /etc/debian_version ]]
then
  alias sysupgrade='sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade'
elif [[ -f /etc/arch-release ]] then
  alias sysupgrade='sudo pacman -Syyu'
fi

# AWS stuff
function aws-cfn-validate() {
    if [[ -n "$1" ]]; then
        aws cloudformation validate-template --template-body "file://$1"
    else
        echo 'Need a parameter: Usage aws-cfn-validate $file'
    fi
}

if [[ -f ~/.ssh/environment ]]
then
    source ~/.ssh/environment
fi

# Source some docker relatet variables
if [[ -f ~/.zshrc_custom/docker.sh ]]
then
    source ~/.zshrc_custom/docker.sh
fi

if [[ -f ~/bin/az.completion ]]
then
    source ~/bin/az.completion
fi
